# Generated by Django 5.2.17 on 2026-09-09 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iam", "0002_seed_departments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="full_name",
        ),
        migrations.AddField(
            model_name="user",
            name="dsp_access",
            field=models.BooleanField(default=False, verbose_name="Допуск к ДСП"),
        ),
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Email (для SMTP-дайджестов)"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                default="",
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_cyrillic_name",
                        message="Допустимы только кириллица, пробел и дефис.",
                        regex="^[А-ЯЁа-яё]+(?:[\\- ][А-ЯЁа-яё]+)*$",
                    )
                ],
                verbose_name="Имя",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                default="",
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_cyrillic_name",
                        message="Допустимы только кириллица, пробел и дефис.",
                        regex="^[А-ЯЁа-яё]+(?:[\\- ][А-ЯЁа-яё]+)*$",
                    )
                ],
                verbose_name="Фамилия",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="middle_name",
            field=models.CharField(
                blank=True,
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_cyrillic_name",
                        message="Допустимы только кириллица, пробел и дефис.",
                        regex="^[А-ЯЁа-яё]+(?:[\\- ][А-ЯЁа-яё]+)*$",
                    )
                ],
                verbose_name="Отчество",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="position",
            field=models.CharField(
                default="", max_length=200, verbose_name="Должность"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Активен"),
                    ("blocked", "Заблокирован"),
                    ("password_change_required", "Требуется смена пароля"),
                ],
                default="active",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="personnel_number",
            field=models.CharField(
                max_length=16,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_personnel_number",
                        message="Табельный номер: только цифры и дефис, длина от 4 до 16 символов.",
                        regex="^[0-9-]{4,16}$",
                    )
                ],
                verbose_name="Табельный номер",
            ),
        ),
    ]
