# Generated by Django 5.2.17 on 2026-09-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iam", "0003_remove_user_full_name_user_dsp_access_user_email_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="department",
            constraint=models.UniqueConstraint(
                fields=("name", "parent"), name="unique_department_name_per_parent"
            ),
        ),
    ]
