# Generated by Django 5.2.17 on 2026-09-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iam", "0004_department_unique_department_name_per_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="totp_secret",
            field=models.CharField(
                blank=True, editable=False, max_length=64, verbose_name="Секрет TOTP"
            ),
        ),
    ]
