# Generated by Django 5.2.17 on 2026-09-10 10:43, ручные правки:
# переименован под смысл + добавлена RunPython-переклассификация role=curator.

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def reassign_curator_to_controller_lawyer(apps, schema_editor):
    """Роль «Куратор службы» упразднена решением Заказчика — весь
    функционал передан роли непосредственно выше по
    User.ROLE_PRIVILEGE_ORDER (CONTROLLER_LAWYER, см. apps/iam/models.py).
    Существующие учётные записи с role="curator" переклассифицируются
    сюда же, а не оставляются со значением, которого с этой миграции
    больше нет в Role.choices ("не забудь её отовсюду вырезать" — включая
    уже сохранённые данные, не только код). choices на CharField не
    ограничение уровня БД, так что без этого шага такие строки остались
    бы валидны физически, но не проходили бы full_clean()/формы — тихая
    несогласованность данных вместо явной миграции."""
    User = apps.get_model("iam", "User")
    User.objects.filter(role="curator").update(role="controller_lawyer")


def noop_reverse(apps, schema_editor):
    # Обратная миграция не восстанавливает, какие именно пользователи были
    # curator до forward-шага — это разрушающее преобразование (переход
    # многие-в-одно), реверс в общем случае невозможен. Оставлено пустым
    # намеренно, а не поднимает NotImplementedError: откат этой миграции
    # (AlterField.role тоже необратим по данным по той же причине) не
    # должен падать сам по себе — предполагается, что откат используется
    # только для отмены самой схемы, не для восстановления бизнес-данных.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("iam", "0005_user_totp_secret"),
    ]

    operations = [
        migrations.RunPython(reassign_curator_to_controller_lawyer, noop_reverse),
        migrations.AddField(
            model_name="user",
            name="password_changed_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Пароль изменён"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("reader", "Читатель"),
                    ("methodist", "Методист подразделения"),
                    ("controller_lawyer", "Контролёр / Юрист"),
                    ("security_officer", "Офицер ИБ"),
                    ("administrator", "Администратор"),
                ],
                default="reader",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="PasswordHistoryEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("password_hash", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись истории паролей",
                "verbose_name_plural": "История паролей",
                "ordering": ["-created_at"],
            },
        ),
    ]
