# Generated by Django 5.2.17 on 2026-09-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0007_totp_secret_encryption_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedLoginTicket',
            fields=[
                ('digest', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='auth_version',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_last_step',
            field=models.BigIntegerField(default=-1, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_pending_secret',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_pending_until',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
