apiVersion: 1

datasources:
  - name: Infrastructure Prometheus
    uid: infra-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: false
    jsonData:
      timeInterval: 15s
