# Generated by Django 5.2.17 on 2026-09-10 21:38

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seed_ocr_review_queue'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=200)),
                ('args', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'indexes': [models.Index(fields=['delivered_at', 'next_attempt_at'], name='outbox_pending_idx')],
            },
        ),
    ]
