# Generated by Django 5.2.17 on 2026-09-09 18:46

import django.contrib.postgres.fields.ranges
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("cancels", "Отменяет"),
                            ("amends", "Вносит изменения в"),
                            ("replaces", "Принят взамен"),
                            ("approves_template", "Утверждает форму"),
                            ("references", "Ссылается на"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, verbose_name="Описание затронутых пунктов"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Связь версионности",
                "verbose_name_plural": "Связи версионности",
            },
        ),
        migrations.CreateModel(
            name="DocumentStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("active", "Действует"),
                            ("active_amended", "Действует с изм."),
                            ("revoked", "Утратил силу"),
                            ("archived", "Архив"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "period",
                    django.contrib.postgres.fields.ranges.DateTimeRangeField(
                        verbose_name="Период действия статуса (valid_from, valid_to)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Историческая запись статуса",
                "verbose_name_plural": "История статусов (SCD-2)",
                "ordering": ["document", "period"],
            },
        ),
        migrations.CreateModel(
            name="NormativeDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reg_number",
                    models.CharField(
                        max_length=64, verbose_name="Регистрационный номер"
                    ),
                ),
                ("reg_date", models.DateField(verbose_name="Дата регистрации")),
                (
                    "effective_date",
                    models.DateField(verbose_name="Дата вступления в силу"),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("order", "Приказ директора"),
                            ("directive", "Распоряжение"),
                            ("regulation", "Положение"),
                            ("sto", "СТО"),
                            ("instruction", "Инструкция"),
                            ("procedure", "Регламент"),
                        ],
                        max_length=32,
                        verbose_name="Вид документа",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=500, verbose_name="Наименование"),
                ),
                ("summary", models.TextField(blank=True, verbose_name="Аннотация")),
                (
                    "access_level",
                    models.CharField(
                        choices=[("general", "Общий"), ("restricted", "ДСП")],
                        default="general",
                        max_length=16,
                        verbose_name="Уровень доступа",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("active", "Действует"),
                            ("active_amended", "Действует с изм."),
                            ("revoked", "Утратил силу"),
                            ("archived", "Архив"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "files_original",
                    models.FileField(
                        upload_to="documents/originals/%Y/%m/",
                        verbose_name="Скан оригинала (PDF/A)",
                    ),
                ),
                (
                    "files_original_sha256",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="SHA-256 оригинала"
                    ),
                ),
                (
                    "files_editable",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documents/editable/%Y/%m/",
                        verbose_name="Редактируемый файл",
                    ),
                ),
                (
                    "ocr_confidence",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="OCR Confidence Score",
                    ),
                ),
            ],
            options={
                "verbose_name": "Нормативно-распорядительный документ",
                "verbose_name_plural": "Нормативно-распорядительные документы",
                "ordering": ["-reg_date"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
                "ordering": ["name"],
            },
        ),
    ]
