# Generated by Django 5.2.17 on 2026-09-09 18:46

import django.contrib.postgres.constraints
import django.contrib.postgres.operations
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        ("iam", "0001_initial"),
    ]

    operations = [
        # Требуется для ExclusionConstraint на DateTimeRangeField (ТЗ 4.2.3:
        # tstzrange + EXCLUDE USING gist).
        django.contrib.postgres.operations.BtreeGistExtension(),
        migrations.AddField(
            model_name="normativedocument",
            name="applied_depts",
            field=models.ManyToManyField(
                blank=True,
                related_name="applicable_documents",
                to="iam.department",
                verbose_name="Подразделения применения",
            ),
        ),
        migrations.AddField(
            model_name="normativedocument",
            name="issuer_dept",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="issued_documents",
                to="iam.department",
                verbose_name="Служба-эмитент",
            ),
        ),
        migrations.AddField(
            model_name="documentstatushistory",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_history",
                to="documents.normativedocument",
            ),
        ),
        migrations.AddField(
            model_name="documentrelation",
            name="from_document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relations_from",
                to="documents.normativedocument",
            ),
        ),
        migrations.AddField(
            model_name="documentrelation",
            name="to_document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relations_to",
                to="documents.normativedocument",
            ),
        ),
        migrations.AddField(
            model_name="normativedocument",
            name="category_tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="documents",
                to="documents.tag",
                verbose_name="Теги",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentstatushistory",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[("document", "="), ("period", "&&")],
                name="exclude_overlapping_status_periods",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentrelation",
            constraint=models.UniqueConstraint(
                fields=("from_document", "to_document", "relation_type"),
                name="unique_document_relation",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentrelation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("from_document", models.F("to_document")), _negated=True
                ),
                name="document_relation_no_self_reference",
            ),
        ),
        migrations.AddIndex(
            model_name="normativedocument",
            index=models.Index(
                fields=["reg_number"], name="documents_n_reg_num_bdc0dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="normativedocument",
            index=models.Index(fields=["status"], name="documents_n_status_1bfe95_idx"),
        ),
    ]
