# Generated by Django 5.2.17 on 2026-09-09 19:40

import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="normativedocument",
            name="files_editable",
            field=models.FileField(
                blank=True,
                null=True,
                storage=apps.core.storage.working_storage,
                upload_to="documents/editable/%Y/%m/",
                verbose_name="Редактируемый файл",
            ),
        ),
        migrations.AlterField(
            model_name="normativedocument",
            name="files_original",
            field=models.FileField(
                storage=apps.core.storage.originals_storage,
                upload_to="documents/originals/%Y/%m/",
                verbose_name="Скан оригинала (PDF/A)",
            ),
        ),
    ]
