# Generated by Django 5.2.17 on 2026-09-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_alter_normativedocument_files_editable_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="normativedocument",
            name="declassification_date",
            field=models.DateField(
                blank=True,
                help_text="Только для документов ДСП — срок хранения отсчитывается от неё, не от reg_date.",
                null=True,
                verbose_name="Дата рассекречивания",
            ),
        ),
        migrations.AddField(
            model_name="normativedocument",
            name="retention_category",
            field=models.CharField(
                choices=[
                    ("orders_core", "Приказы по основной деятельности"),
                    ("orders_personnel", "Приказы по личному составу"),
                    ("directives_operational", "Распоряжения оперативного характера"),
                    ("acts_investigation", "Акты расследований ДТП, сходов, Н-1"),
                    ("permits_eh", "Наряды-допуски, протоколы испытаний ЭХ"),
                    ("templates_approved", "Бланки и типовые формы (утверждённые)"),
                    ("archival_scans", "Архивные сканы (до 2017 г.)"),
                    ("dsp", "Документы ДСП"),
                ],
                default="orders_core",
                max_length=32,
                verbose_name="Категория срока хранения",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="normativedocument",
            name="retention_mode",
            field=models.CharField(
                choices=[
                    ("governance", "Governance (снимается Офицером ИБ + Контролёром)"),
                    ("compliance", "Compliance (не снимается никем, включая root)"),
                ],
                default="compliance",
                editable=False,
                max_length=16,
                verbose_name="Режим WORM",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="normativedocument",
            name="retention_until",
            field=models.DateField(
                blank=True,
                editable=False,
                null=True,
                verbose_name="Хранить до (NULL = бессрочно/не определено)",
            ),
        ),
    ]
