# Generated by Django 5.2.17 on 2026-09-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_normativedocument_declassification_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="normativedocument",
            name="ocr_body",
            field=models.TextField(
                blank=True, verbose_name="Извлечённый текст скана (OCR)"
            ),
        ),
    ]
