# Generated by Django 5.2.17 on 2026-09-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0005_normativedocument_ocr_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="normativedocument",
            name="ocr_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("modern_nrd", "Современные НРД (с 2018 г.)"),
                    ("mixed_forms", "Бланки со смешанным вводом"),
                    ("archive", "Архивный фонд (1970–2017)"),
                    ("schemes", "Схемы и чертежи"),
                ],
                max_length=20,
                verbose_name="Категория качества OCR",
            ),
        ),
        migrations.AddField(
            model_name="normativedocument",
            name="ocr_status",
            field=models.CharField(
                choices=[
                    ("not_processed", "OCR не выполнялся"),
                    ("indexed", "Проиндексирован (автоматически)"),
                    ("needs_review", "Требует ручной верификации"),
                ],
                default="not_processed",
                max_length=16,
                verbose_name="Статус распознавания",
            ),
        ),
    ]
