# Generated by Django 5.2.17 on 2026-09-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0006_normativedocument_ocr_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="normativedocument",
            name="declassification_date",
            field=models.DateField(
                blank=True,
                help_text="Только для документов ДСП — срок хранения отсчитывается от неё, а не от даты регистрации.",
                null=True,
                verbose_name="Дата рассекречивания",
            ),
        ),
    ]
