# Generated by Django 5.2.17 on 2026-09-10 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0007_alter_normativedocument_declassification_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentrelation",
            name="from_document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relations_from",
                to="documents.normativedocument",
                verbose_name="Документ-источник",
            ),
        ),
        migrations.AlterField(
            model_name="documentrelation",
            name="relation_type",
            field=models.CharField(
                choices=[
                    ("cancels", "Отменяет"),
                    ("amends", "Вносит изменения в"),
                    ("replaces", "Принят взамен"),
                    ("approves_template", "Утверждает форму"),
                    ("references", "Ссылается на"),
                ],
                max_length=32,
                verbose_name="Вид связи",
            ),
        ),
        migrations.AlterField(
            model_name="documentrelation",
            name="to_document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relations_to",
                to="documents.normativedocument",
                verbose_name="Связанный документ",
            ),
        ),
        migrations.AlterConstraint(
            model_name="documentrelation",
            name="unique_document_relation",
            constraint=models.UniqueConstraint(
                fields=("from_document", "to_document", "relation_type"),
                name="unique_document_relation",
                violation_error_message="Такая связь между этими документами уже заведена.",
            ),
        ),
    ]
