# Generated by Django 5.2.17 on 2026-09-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_alter_documentrelation_from_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='normativedocument',
            name='edit_version',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
