# Generated by Django 5.2.17 on 2026-09-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0009_normativedocument_edit_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentstatushistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("active", "Действует"),
                    ("active_amended", "Действует с изм."),
                    ("revoked", "Утратил силу"),
                    ("annulled", "Аннулирован"),
                    ("archived", "Архив"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="normativedocument",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("active", "Действует"),
                    ("active_amended", "Действует с изм."),
                    ("revoked", "Утратил силу"),
                    ("annulled", "Аннулирован"),
                    ("archived", "Архив"),
                ],
                default="draft",
                max_length=16,
            ),
        ),
    ]
