# Generated by Django 5.2.17 on 2026-09-11 12:42

import apps.core.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0010_alter_documentstatushistory_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="normativedocument",
            name="files_editable",
            field=models.FileField(
                blank=True,
                null=True,
                storage=apps.core.storage.working_storage,
                upload_to="documents/editable/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["docx", "xlsx"]
                    )
                ],
                verbose_name="Редактируемый файл",
            ),
        ),
        migrations.AlterField(
            model_name="normativedocument",
            name="files_original",
            field=models.FileField(
                storage=apps.core.storage.originals_storage,
                upload_to="documents/originals/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
                verbose_name="Скан оригинала (PDF/A)",
            ),
        ),
    ]
