# Generated by Django 5.2.17 on 2026-09-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0012_documentbookmark"),
    ]

    operations = [
        migrations.AddField(
            model_name="normativedocument",
            name="summary_is_auto",
            field=models.BooleanField(
                default=False,
                editable=False,
                verbose_name="Аннотация собрана автоматически",
            ),
        ),
    ]
