# Generated by Django 5.2.17 on 2026-09-09 21:05

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ThesaurusEntry",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.SlugField(
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Идентификатор записи",
                    ),
                ),
                (
                    "canonical",
                    models.CharField(
                        max_length=500, verbose_name="Каноническая форма термина"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("org.l1", "Аппарат управления (уровень 1)"),
                            ("org.l2", "Отраслевые службы (уровень 2)"),
                            ("org.l3.depot", "Обособленные парки (уровень 3)"),
                            ("org.l3.district", "Районы и дистанции (уровень 3)"),
                            ("org.l4", "Линейные подразделения (уровень 4)"),
                            ("doc.type", "Типы нормативно-распорядительных документов"),
                            ("doc.status", "Статусы жизненного цикла документа"),
                            ("doc.form", "Бланки, формы актов и протоколов"),
                            ("tech.vehicle", "Подвижной состав и изготовители"),
                            ("tech.energy", "Энергохозяйство и контактная сеть"),
                            ("tech.track", "Путевое хозяйство"),
                            ("incident", "Происшествия и инциденты"),
                            (
                                "hse",
                                "Охрана труда, промышленная и пожарная безопасность, БДД",
                            ),
                            (
                                "role.person",
                                "Должности линейного и инженерного персонала",
                            ),
                            ("role.ais", "Роли в АИС «БЗ ГЭТ»"),
                            ("process", "Производственные процессы"),
                            ("ais.system", "Термины самой АИС"),
                            ("reg.external", "Внешние нормативные акты"),
                        ],
                        max_length=32,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SD", "Служба движения"),
                            ("SPS", "Служба подвижного состава"),
                            ("EKH", "Энергохозяйство (Служба ЭХ)"),
                            ("SPUT", "Служба пути"),
                            ("ASIT", "Служба АСиИТ"),
                            ("OTPB", "Служба ОТ, ПБ и БДД"),
                            ("IB", "Служба информационной безопасности"),
                            ("APPARAT", "Аппарат управления"),
                            ("YUR", "Юридический отдел"),
                        ],
                        max_length=16,
                        null=True,
                        verbose_name="Служба-владелец (null = общепредприятийский термин)",
                    ),
                ),
                (
                    "short_forms",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Аббревиатуры и шифры",
                    ),
                ),
                (
                    "synonyms",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Синонимы",
                    ),
                ),
                (
                    "synonyms_legacy",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200),
                        blank=True,
                        default=list,
                        size=None,
                        verbose_name="Устаревшие обозначения (вес 0.3, только для поиска по историческому фонду)",
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        default=1.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name="Вес расширения запроса",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Источник термина"
                    ),
                ),
                (
                    "ambiguous",
                    models.BooleanField(
                        default=False,
                        verbose_name="Аббревиатура конфликтует с другой записью (см. ambiguity_registry файла)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("verified", "Подтверждено куратором"),
                            ("rejected", "Отклонено"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "verbose_name": "Словарная статья тезауруса",
                "verbose_name_plural": "Тезаурус (Smart Search)",
                "ordering": ["canonical"],
                "indexes": [
                    models.Index(
                        fields=["category"], name="search_ocr__categor_af62bd_idx"
                    ),
                    models.Index(
                        fields=["service"], name="search_ocr__service_5b603e_idx"
                    ),
                    models.Index(
                        fields=["status"], name="search_ocr__status_fe1779_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("canonical"),
                        name="unique_thesaurus_canonical_ci",
                    )
                ],
            },
        ),
    ]
