# Generated by Django 5.2.17 on 2026-09-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search_ocr", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thesaurusentry",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("verified", "Подтверждено"),
                    ("rejected", "Отклонено"),
                ],
                default="draft",
                max_length=16,
            ),
        ),
    ]
