# Generated by Django 5.2.17 on 2026-09-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search_ocr", "0002_alter_thesaurusentry_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThesaurusAmbiguity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "abbr",
                    models.CharField(
                        max_length=100, verbose_name="Аббревиатура (как в файле)"
                    ),
                ),
                (
                    "abbr_normalized",
                    models.CharField(
                        editable=False,
                        max_length=100,
                        unique=True,
                        verbose_name="Аббревиатура (нормализованная — ключ upsert/поиска)",
                    ),
                ),
                (
                    "candidates",
                    models.JSONField(
                        default=list,
                        verbose_name="Кандидаты расшифровки: [{id, weight, reason}, ...]",
                    ),
                ),
                (
                    "disambiguation",
                    models.TextField(
                        blank=True,
                        verbose_name="Правило разрешения неоднозначности (свободный текст файла)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Неоднозначная аббревиатура",
                "verbose_name_plural": "Реестр неоднозначностей тезауруса",
                "ordering": ["abbr"],
            },
        ),
    ]
