# Generated by Django 5.2.17 on 2026-09-10 11:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search_ocr", "0003_thesaurusambiguity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="thesaurusambiguity",
            name="candidates",
        ),
        migrations.AlterField(
            model_name="thesaurusambiguity",
            name="abbr",
            field=models.CharField(
                db_index=True, max_length=100, verbose_name="Аббревиатура (как в файле)"
            ),
        ),
        migrations.CreateModel(
            name="ThesaurusAmbiguityCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "weight",
                    models.FloatField(
                        default=1.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name="Вес кандидата (candidates[].weight файла)",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        verbose_name="Обоснование (candidates[].reason файла)",
                    ),
                ),
                (
                    "ambiguity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="search_ocr.thesaurusambiguity",
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ambiguity_candidates",
                        to="search_ocr.thesaurusentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Кандидат неоднозначной аббревиатуры",
                "verbose_name_plural": "Кандидаты неоднозначных аббревиатур",
                "ordering": ["-weight"],
                "indexes": [
                    models.Index(
                        fields=["entry"], name="search_ocr__entry_i_bdc908_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ambiguity", "entry"), name="unique_ambiguity_candidate"
                    )
                ],
            },
        ),
    ]
