# Generated by Django 5.2.17 on 2026-09-09 18:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateFamily",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Наименование семейства форм"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Семейство форм",
                "verbose_name_plural": "Семейства форм",
            },
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        max_length=16, verbose_name="Версия (v1.0, v2.0…)"
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("major", "Новая редакция"),
                            ("minor", "Корректировка"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Активна"), ("superseded", "superseded")],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "file_editable",
                    models.FileField(
                        upload_to="templates/editable/%Y/",
                        verbose_name="Защищённый рабочий бланк (.docx/.xlsx)",
                    ),
                ),
                (
                    "file_sample",
                    models.FileField(
                        upload_to="templates/samples/%Y/",
                        verbose_name="Эталонный образец заполнения (.pdf)",
                    ),
                ),
                ("download_count", models.PositiveIntegerField(default=0)),
                (
                    "last_reviewed_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата последнего пересмотра"
                    ),
                ),
                (
                    "approving_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_templates",
                        to="documents.normativedocument",
                        verbose_name="Утверждающий приказ",
                    ),
                ),
                (
                    "previous_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="templates_bank.template",
                    ),
                ),
                (
                    "revoking_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revoked_templates",
                        to="documents.normativedocument",
                        verbose_name="Отменяющий приказ",
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supersedes",
                        to="templates_bank.template",
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="templates",
                        to="templates_bank.templatefamily",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бланк / шаблон",
                "verbose_name_plural": "Бланки и шаблоны",
                "ordering": ["family", "-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("family", "version"), name="unique_template_version"
                    )
                ],
            },
        ),
    ]
