# Generated by Django 5.2.17 on 2026-09-11 12:42

import apps.core.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates_bank", "0003_alter_template_file_editable_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="file_editable",
            field=models.FileField(
                storage=apps.core.storage.originals_storage,
                upload_to="templates/editable/%Y/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["docx", "xlsx"]
                    )
                ],
                verbose_name="Защищённый рабочий бланк (.docx/.xlsx)",
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="file_sample",
            field=models.FileField(
                storage=apps.core.storage.originals_storage,
                upload_to="templates/samples/%Y/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
                verbose_name="Эталонный образец заполнения (.pdf)",
            ),
        ),
    ]
