# Generated by Django 5.2.17 on 2026-09-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates_bank", "0004_alter_template_file_editable_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Активна"),
                    ("superseded", "Заменена новой редакцией"),
                ],
                default="active",
                max_length=16,
            ),
        ),
    ]
