# Generated by Django 5.2.17 on 2026-09-09 18:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("document.published", "Документ опубликован"),
                            ("document.revoked", "Документ отменён"),
                            ("template.updated", "Бланк обновлён (минорно)"),
                            ("template.superseded", "Бланк заменён новой редакцией"),
                            ("session.login", "Вход в систему"),
                            ("session.logout", "Выход из системы"),
                            ("export.restricted", "Выгрузка документа «ДСП»"),
                            ("archive.download", "Скачивание архивного бланка"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "actor_personnel_number",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        verbose_name="Табельный номер оператора (снимок на момент события)",
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Тип объекта"
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Идентификатор объекта"
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Реквизиты события"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Запись журнала аудита",
                "verbose_name_plural": "Журнал аудита (WORM)",
                "ordering": ["-created_at"],
            },
        ),
    ]
