# Generated by Django 5.2.17 on 2026-09-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0005_worm_truncate_trigger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("document.published", "Документ опубликован"),
                    ("document.revoked", "Документ отменён"),
                    ("template.updated", "Бланк обновлён (минорно)"),
                    ("template.superseded", "Бланк заменён новой редакцией"),
                    ("session.login", "Вход в систему"),
                    ("session.logout", "Выход из системы"),
                    ("export.restricted", "Выгрузка документа «ДСП»"),
                    ("archive.download", "Скачивание архивного бланка"),
                    ("user.role_elevated", "Повышение роли пользователя"),
                    (
                        "document.retention_category_changed",
                        "Изменена категория срока хранения",
                    ),
                    (
                        "document.retention_expired_at_intake",
                        "Срок хранения уже истёк на момент регистрации",
                    ),
                ],
                max_length=64,
            ),
        ),
    ]
