# Generated by Django 5.2.17 on 2026-09-10 13:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0011_alter_auditlog_event_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["event_type", "actor_personnel_number", "created_at"],
                name="audit_lockout_window_idx",
            ),
        ),
    ]
