# Generated by Django 5.2.17 on 2026-09-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0012_auditlog_audit_lockout_window_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("document.published", "Документ опубликован"),
                    ("document.revoked", "Документ отменён"),
                    ("document.status_changed", "Изменён статус документа"),
                    ("template.updated", "Бланк обновлён (минорно)"),
                    ("template.superseded", "Бланк заменён новой редакцией"),
                    ("session.login", "Вход в систему"),
                    ("session.logout", "Выход из системы"),
                    ("session.login_failed", "Неудачная попытка входа"),
                    ("export.restricted", "Выгрузка документа «ДСП»"),
                    ("archive.download", "Скачивание архивного бланка"),
                    ("user.role_elevated", "Повышение роли пользователя"),
                    ("user.role_changed", "Изменение роли пользователя"),
                    ("user.totp_reset", "Администратор сбросил 2FA (TOTP)"),
                    (
                        "document.retention_category_changed",
                        "Изменена категория срока хранения",
                    ),
                    (
                        "document.retention_expired_at_intake",
                        "Срок хранения уже истёк на момент регистрации",
                    ),
                    ("thesaurus.updated", "Обновление тезауруса (импорт)"),
                    ("document.ocr_completed", "Распознавание OCR завершено"),
                    ("document.ocr_failed", "Распознавание OCR не выполнено"),
                    (
                        "upload.malware_detected",
                        "Обнаружен вредоносный файл при загрузке",
                    ),
                    ("upload.macro_rejected", "Отклонён файл с макросами/ActiveX"),
                    ("audit_log.exported", "Экспорт журнала аудита"),
                ],
                max_length=64,
            ),
        ),
    ]
